// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAykYVWJ3AM9VkHoZYuoUHaQIdBkZlWg0E',
    appId: '1:356301238181:web:9620cc275d4b5f7466c24c',
    messagingSenderId: '356301238181',
    projectId: 'finance-app-a1603',
    authDomain: 'finance-app-a1603.firebaseapp.com',
    storageBucket: 'finance-app-a1603.firebasestorage.app',
    measurementId: 'G-M88VDN3DDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF1zj8lwb01yQC2122j1pd08LV-4210q4',
    appId: '1:356301238181:android:9be16c5957ea4fc266c24c',
    messagingSenderId: '356301238181',
    projectId: 'finance-app-a1603',
    storageBucket: 'finance-app-a1603.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAykYVWJ3AM9VkHoZYuoUHaQIdBkZlWg0E',
    appId: '1:356301238181:web:218b6bf82473b96266c24c',
    messagingSenderId: '356301238181',
    projectId: 'finance-app-a1603',
    authDomain: 'finance-app-a1603.firebaseapp.com',
    storageBucket: 'finance-app-a1603.firebasestorage.app',
    measurementId: 'G-K5T0NDM5F1',
  );

}